Models/SanPham.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doanphanmem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CTDATHANG = new HashSet<CTDATHANG>();
            this.Vourcher = new HashSet<Vourcher>();
            this.YeuThich = new HashSet<YeuThich>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> GiaSp { get; set; }
        public Nullable<int> GiaGiam { get; set; }
        public string Hinh1 { get; set; }
        public string Hinh2 { get; set; }
        public string Hinh3 { get; set; }
        public string Hinh4 { get; set; }
        public string Mota { get; set; }
        public string Thongso { get; set; }
        public Nullable<int> Soluongton { get; set; }
        public int MaLoai { get; set; }
        public Nullable<int> Mamau { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDATHANG> CTDATHANG { get; set; }
        public virtual Mau Mau { get; set; }
        public virtual PhanLoai PhanLoai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vourcher> Vourcher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeuThich> YeuThich { get; set; }
    }
}

Controllers/GioHangController.cs
using Doanphanmem.Models;
using Microsoft.AspNet.SignalR;
using PayPal.Api;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using static Doanphanmem.Pattern.Strategy;

namespace Doanphanmem.Controllers
{
    //chain
    //public interface IThanhToanHandler
    //{
    //    void XuLyThanhToan(HttpContextBase httpContext, List<MatHangMua> gioHang);
    //}

    //public class ThanhToanBangPayPalHandler : IThanhToanHandler
    //{
    //    QL_CHDTEntities db = new QL_CHDTEntities();
    //    private readonly Func<double> _tinhTongTienvnd;
    //    private readonly Func<double> _tinhTongTien;

    //    public ThanhToanBangPayPalHandler(Func<double> tinhTongTien, Func<double> tinhTongTienvnd)
    //    {
    //        _tinhTongTien = tinhTongTien;
    //        _tinhTongTienvnd = tinhTongTienvnd;
    //    }

    //    public void XuLyThanhToan(HttpContextBase httpContext, List<MatHangMua> gioHang)
    //    {
    //        KhachHang kh = httpContext.Session["taikhoan"] as KhachHang;
    //        if (kh == null || gioHang == null || gioHang.Count == 0)
    //        {
    //            return;
    //        }
    //        // Các bước xử lý thanh toán PayPal
    //        var apiContext = PaypalConfiguration.GetAPIContext();
    //        string paymentId = null;
    //        string payerId = httpContext.Request.Params["PayerID"];

    //        // Xử lý khi không có thông tin PayerID
    //        if (string.IsNullOrEmpty(payerId))
    //        {
    //            string baseURI = httpContext.Request.Url.Scheme + "://" + httpContext.Request.Url.Authority + "/GioHang/PaymentWithPayPal?";
    //            var guid = Convert.ToString((new Random()).Next(100000));
    //            var createdPayment = CreatePayment(apiContext, baseURI + "guid=" + guid);
    //            var links = createdPayment.links.GetEnumerator();
    //            string paypalRedirectUrl = null;

    //            // Lấy đường dẫn redirect từ PayPal
    //            while (links.MoveNext())
    //            {
    //                Links lnk = links.Current;
    //                if (lnk.rel.ToLower().Trim().Equals("approval_url"))
    //                {
    //                    paypalRedirectUrl = lnk.href;
    //                    break;
    //                }
    //            }

    //            // Lưu paymentID vào session
    //            httpContext.Session.Add(guid, createdPayment.id);
    //            // Redirect đến PayPal
    //            httpContext.Response.Redirect(paypalRedirectUrl, true);
    //        }
    //        else
    //        {
    //            // Xử lý thanh toán khi có thông tin PayerID
    //            var guid = httpContext.Request.Params["guid"];
    //            var executedPayment = ExecutePayment(apiContext, payerId, httpContext.Session[guid] as string);
    //            if (executedPayment.state.ToLower() != "approved")
    //            {
    //                return;
    //            }
    //            else
    //            {

    //            }
    //        }

    //        // Các bước xử lý đơn hàng và giỏ hàng
    //        // Thêm dữ liệu vào đơn hàng

    //    }

    //    private Payment CreatePayment(APIContext apiContext, string redirectUrl)
    //    {
    //        var itemList = new ItemList
    //        {
    //            items = new List<Item>
    //            {
    //                new Item
    //                {
    //                    name = "Item Name",
    //                    currency = "USD",
    //                    price = _tinhTongTienvnd().ToString(),
    //                    quantity = "1",
    //                    sku = "sku"
    //                }
    //            }
    //        };

    //        var payer = new Payer
    //        {
    //            payment_method = "paypal"
    //        };

    //        var redirUrls = new RedirectUrls
    //        {
    //            cancel_url = redirectUrl + "&Cancel=true",
    //            return_url = redirectUrl
    //        };

    //        var details = new Details
    //        {
    //            tax = "0",
    //            shipping = "0",
    //            subtotal = _tinhTongTienvnd().ToString()
    //        };

    //        var amount = new Amount
    //        {
    //            currency = "USD",
    //            total = _tinhTongTienvnd().ToString(), // Tổng giá trị thanh toán trong USD
    //            details = details
    //        };

    //        var transactionList = new List<Transaction>
    //        {
    //            new Transaction
    //            {
    //                description = "Invoice",
    //                invoice_number = Guid.NewGuid().ToString(),
    //                amount = amount,
    //                item_list = itemList
    //            }
    //        };

    //        var payment = new Payment
    //        {
    //            intent = "sale",
    //            payer = payer,
    //            transactions = transactionList,
    //            redirect_urls = redirUrls
    //        };
    //        return payment.Create(apiContext);
    //    }

    //    private PayPal.Api.Payment payment;

    //    private Payment ExecutePayment(APIContext apiContext, string payerId, string paymentId)
    //    {
    //        var paymentExecution = new PaymentExecution()
    //        {
    //            payer_id = payerId
    //        };
    //        this.payment = new Payment()
    //        {
    //            id = paymentId
    //        };
    //        return this.payment.Execute(apiContext, paymentExecution);
    //    }

    //}


    //public class ThanhToanTrucTiepHandler : IThanhToanHandler
    //{
    //    QL_CHDTEntities db = new QL_CHDTEntities();

    //    private readonly Func<double> _tinhTongTien;

    //    public ThanhToanTrucTiepHandler(Func<double> tinhTongTien)
    //    {
    //        _tinhTongTien = tinhTongTien;
    //    }
    //    public void XuLyThanhToan(HttpContextBase httpContext, List<MatHangMua> gioHang)
    //    {
    //        // Lấy thông tin khách hàng từ Session
    //        KhachHang kh = httpContext.Session["taikhoan"] as KhachHang;

    //        // Kiểm tra nếu khách hàng không tồn tại hoặc giỏ hàng trống, thoát khỏi hàm
    //        if (kh == null || gioHang == null || gioHang.Count == 0)
    //        {
    //            return;
    //        }

    //        // Thêm dữ liệu vào đơn hàng
    //        DONDATHANG donhang = new DONDATHANG
    //        {
    //            MaKH = kh.MaKH,
    //            NgayDH = DateTime.Now,
    //            Trigia = (decimal)_tinhTongTien(),
    //            Dagiao = false,
    //            Tennguoinhan = kh.TenKH,
    //            Diachinhan = kh.DiaChi,
    //            Dienthoainhan = kh.sdt.ToString(),
    //            HTThanhtoan = true,
    //            HTGiaohang = false,
    //            GiaoHang = false
    //        };

    //        // Lưu đơn hàng vào cơ sở dữ liệu
    //        db.DONDATHANG.Add(donhang);

    //        // Thêm vào chi tiết đơn hàng
    //        foreach (var sanpham in gioHang)
    //        {
    //            CTDATHANG ct = new CTDATHANG
    //            {
    //                SODH = donhang.SODH,
    //                MaSP = sanpham.MaDT,
    //                Soluong = sanpham.Soluong,
    //                Dongia = (decimal)_tinhTongTien()
    //            };
    //            db.CTDATHANG.Add(ct);
    //        }
    //        db.SaveChanges();
    //        // Xóa giỏ hàng
    //        httpContext.Session["GioHang"] = null;

    //    }
    //}

    //public class ChuoiXuLyThanhToan
    //{
    //    private readonly List<IThanhToanHandler> _handlers = new List<IThanhToanHandler>();

    //    public void ThemHandler(IThanhToanHandler handler)
    //    {
    //        _handlers.Add(handler);
    //    }
    //    public void XuLy(HttpContextBase httpContext, List<MatHangMua> gioHang)
    //    {
    //        foreach (var handler in _handlers)
    //        {
    //            handler.XuLyThanhToan(httpContext, gioHang);
    //            // Kiểm tra xem yêu cầu đã được xử lý chưa, nếu có thể thoát ra khỏi vòng lặp
    //            if (ThanhToanDaXuLy(httpContext))
    //            {
    //                break;
    //            }
    //        }
    //    }

    //    private bool ThanhToanDaXuLy(HttpContextBase httpContext)
    //    {
    //        // Kiểm tra điều kiện nào đó để xác định liệu thanh toán đã được xử lý hay không
    //        // Ví dụ: kiểm tra xem đơn hàng đã được đặt hàng thành công hay không
    //        return false;
    //    }
    //}
    public class GioHangController : Controller
    {
        //private readonly ChuoiXuLyThanhToan _chuoiXuLyThanhToan = new ChuoiXuLyThanhToan();

        private ThanhToanContext _thanhToanContext;

        // GET: GioHang
        QL_CHDTEntities db = new QL_CHDTEntities();
        public GioHangController()
        {
            // chain
            Func<double> tinhTongTien = TinhTongTien;
            Func<double> tinhTongTienvnd = TinhTongTienvnd;
            //// Thêm các handler vào chuỗi xử lý thanh toán
            //_chuoiXuLyThanhToan.ThemHandler(new ThanhToanBangPayPalHandler(tinhTongTien, tinhTongTienvnd));
            //_chuoiXuLyThanhToan.ThemHandler(new ThanhToanTrucTiepHandler(tinhTongTien));
            // Strategy
            _thanhToanContext = new ThanhToanContext(new ThanhToanTrucTiepStrategy(TinhTongTien));
        }
        public ActionResult DongYDatHang(bool isDirectPayment)
        {
            // Lựa chọn chiến lược thanh toán dựa vào đầu vào
            if (isDirectPayment)
            {
                _thanhToanContext.SetThanhToanStrategy(new ThanhToanTrucTiepStrategy(() => TinhTongTien()));
            }
            else
            {

Views/SanPhams/DonHangChiTietKH.cshtml
@model List<Doanphanmem.Models.CTDATHANG>
@{
    ViewBag.Title = "DonHangChiTietKH";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align:center">Thông Tin Chi Tiết Đơn Hàng</h2>

<table class="table">
    <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th>Unit Price</th>
        <th>Total Price</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.SanPham.TenSP</td>
            <td>@item.Soluong</td>
            <td>
                @String.Format("{0:0,0}", (item.SanPham.GiaSp)) VNĐ
            </td>
            <td>
                @String.Format("{0:0,0}", (item.Soluong * item.SanPham.GiaSp)) VNĐ
            </td>
        </tr>
    }
    <tr>
        Tổng số lượng sản phẩm: @Model.Sum(b => b.Soluong)
    </tr>
    <tr>Tổng Tiền Đơn Hàng:@String.Format("{0:0,0}", Model.Sum(b => b.SanPham.GiaSp)) VNĐ</tr>
 


</table>

Views/SanPhams/Index.cshtml
@*@model IEnumerable<Doanphanmem.Models.SanPham>*@
@using Doanphanmem.Models
@using PagedList.Mvc
@model PagedList.PagedList<SanPham>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<style>
    :root {
        --maudo: RGB(255, 205, 210);
    }

    .card-equal-height {
        display: flex;
        flex-direction: column;
        height: 100%;
    }

        .card-equal-height .card-body {
            flex-grow: 1;
        }
</style>


<div id="demo" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active"></button>
        <button type="button" data-bs-target="#demo" data-bs-slide-to="1"></button>
        <button type="button" data-bs-target="#demo" data-bs-slide-to="2"></button>
    </div>


    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/Image/bg2.png" alt="" class="d-block w-100" style="height: 750px; object-position: center;">
        </div>
        <div class="carousel-item active">
            <img src="~/Image/bg3.png" alt="" class="d-block w-100" style="height: 750px; object-position: center;">
        </div>
        <div class="carousel-item active">
            <img src="~/Image/bg5.png" alt="" class="d-block w-100" style="height: 750px; object-position: center;">
        </div>
    </div>


    <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
        <span class="carousel-control-prev-icon"></span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
        <span class="carousel-control-next-icon"></span>
    </button>
</div>



@*danh mục sản phâm*@
@Html.Action("layloaisp", "SanPhams")

@* loc san pham*@
<div class="container-fluid mt-5">
    <div class="container-fluid  p-3 text-center mt-4" style="background-color: #1A6DFF; color: white; font-size: 20px; font-weight: bold; ">Sản Phẩm</div>
    <div style="margin-right:50px;margin-top:20px;margin-left:20px;">
        @*<button>
                <a href="@Url.Action("locgia", "SanPhams", new { gia = 7000000 } )"><div class="btn">Dưới 7 triệu </div></a>
            </button>
            <button>
                <a href="@Url.Action("locgia", "SanPhams", new { gia = 4000000 } )"><div class="btn">Dưới 4 triệu </div></a>
            </button>*@

        @using (Html.BeginForm("Index", "SanPhams", FormMethod.Get))
        {
            <p>
                Tên sản phẩm: @Html.TextBox("name")
                Giá từ: @Html.TextBox("minPrice")
                Giá đến: @Html.TextBox("maxPrice")
                Màu sắc: @Html.DropDownList("colorId", ViewBag.MaMau as SelectList, "Chọn màu")
                Loại sản phẩm: @Html.DropDownList("categoryId", ViewBag.MaLoai as SelectList, "Chọn loại")
                <input type="submit" value="Tìm kiếm" class="btn btn-primary" />
            </p>
        }
    </div>
    <div class="row mt-3 p-5">
        @foreach (var sp in Model)
        {
            <div class="col-sm-3 mb-4 product">
                <div class="card card-equal-height">
                    <a href="@Url.Action("SP_giamgia", "SanPhams", new { id = sp.MaSP })">
                        <img src="~/Image/@sp.Hinh1" style="height:250px; width:250px" class="card-img-top" alt="Iphone" height="187">
                        <div class="card-body">
                            <h5 class="card-title">
                                @sp.TenSP -
                                @if (sp.Mamau == 1)
                                {
                                    <p>Trắng</p>


                                }
                                @if (sp.Mamau == 2)
                                {
                                    <p>
                                        Đen

                                    </p>

                                }
                                @if (sp.Mamau == 3)
                                {
                                    <p>
                                        Trắng
                                   
                                    </p>

                                }
                                @if (sp.Mamau == 4)
                                {
                                    <p>
                                        Đỏ
                                

                                    </p>
                                }
                                @if (sp.Mamau == 5)
                                {
                                    <p>
                                        Xanh dương
                                   

                                    </p>
                                }
                                @if (sp.Mamau == 6)
                                {
                                    <p>
                                        Xanh lá cây
                                      

                                    </p>
                                }
                                @if (sp.Mamau == 7)
                                {
                                    <p>
                                        Vàng
                                     

                                    </p>
                                }
                                @if (sp.Mamau == 8)
                                {
                                    <p>
                                        Hồng
                                   

                                    </p>
                                }
                                @if (sp.Mamau == 9)
                                {
                                    <p>
                                        Cam
                                  

                                    </p>
                                }
                                @if (sp.Mamau == 10)
                                {
                                    <p>
                                        Tím
                                  

                                    </p>
                                }
                                @if (sp.Mamau == 11)
                                {
                                    <p>
                                        Xanh đen
                                  

                                    </p>
                                }
                                @if (sp.Mamau == 12)
                                {
                                    <p>
                                        Xám

                                    </p>
                                }
                            </h5>
                            @*<p class="card-text">(@sp.GiaSp*10) VNĐ</p>*@
                            <p class="card-product__price"> @string.Format("{0:#,##0} VND", sp.GiaSp)</p>
                            <div class="row">
                            </div>
                        </div>
                    </a>
                    <a class="btn btn-primary" href="@Url.Action("AddProduct", "GioHang", new{ MaSP = sp.MaSP })">
                        Đặt mua
                    </a>
                </div>
            </div>
        }
    </div>
 
    <!-- Thêm mã phân trang -->
    <br />
    <div style="text-align:center">
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
        <div class="MenuTrang" style="margin-left:500px">
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
        </div>
    </div>
    <style>
        .MenuTrang li {
            display: inline;
        }

        td, th {
            text-align: center;
        }
    </style>
    <!-- Kết thúc -->
    @*bai báo*@
    <div class="container-fluid bg-light text-center " style="background-color: #1A6DFF;">Cửa hàng chuyên cung cấp các loại điện thoại mới nhất </div>

    <div class="container pt-5">
        <div class="row mt-4">
            <div class="col-sm-6 ">
                <div class="card">
                    <img src="~/Image/iphone-14-pro-max-den.png" class="card-img-top" />
                    <div class="card-body">
                        <a href="https://vnexpress.net/iphone-15-pro-max-thua-galaxy-s23-ultra-khi-tha-roi-4660100.html" class="card-title ">iPhone 15 Pro Max thua Galaxy S23 Ultra khi thả rơi</a>
                        <p>iPhone 15 Pro Max bị hư hại nhiều hơn Galaxy S23 Ultra sau bốn lần thả rơi ở các góc khác nhau xuống bề mặt bê tông và thép...</p>
                    </div>
                </div>
            </div>

            <div class="col-sm-6 ">
                <div class="card">
                    <img src="~/Image/iphone-14-pro-max-den.png" class="card-img-top"> </img>
                    <div class="card-body">
                        <a href="https://vnexpress.net/iphone-15-pro-max-thua-galaxy-s23-ultra-khi-tha-roi-4660100.html" class="card-title ">iPhone 15 Pro Max thua Galaxy S23 Ultra khi thả rơi</a>
                        <p>iPhone 15 Pro Max bị hư hại nhiều hơn Galaxy S23 Ultra sau bốn lần thả rơi ở các góc khác nhau xuống bề mặt bê tông và thép...</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="p-5"></div>

Views/SanPhams/SP_giamgia.cshtml
@using Doanphanmem.Models;
@model SanPham
@{
    ViewBag.Title = "laychitietsp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .btn-mh {
        width: 200px;
        border-radius: 5px;
        padding: 10px;
        box-shadow: 0 0 10px rgba(220, 20, 60, 0.1);
    }

        .btn-mh:hover {
            border-radius: 5px;
            background-color: red;
        }

    .t {
        font-size: 40px;
    }
</style>

<style>
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f5f5f5;
    }

    .container {
        max-width: 1200px;
        margin: 20px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(220, 20, 60, 0.5);
    }
</style>
<script src="https://kit.fontawesome.com/383abdf887.js" crossorigin="anonymous"></script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
<div class="row">
    <div id="carouselExampleIndicators" class="carousel slide col-6 ">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="~/Image/@Model.Hinh1" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/Image/@Model.Hinh2" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/Image/@Model.Hinh3" class="d-block w-100" alt="...">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>

    </div>
    <div class="col-6">
        <h2 class="pb-4">@Model.TenSP | Chính hãng VN/A</h2>
        <h3 class="pb-2">Hãng : @Model.PhanLoai.Tenloai</h3>
        <h4 class="pb-2">
            @if (ViewBag.GiaSauGiamGia != null)
            {
                <p>Giá: <del>   @String.Format("{0:0,0}", @Model.GiaSp) VNĐ</del> Giá sau giảm giá:   @String.Format("{0:0,0}", ViewBag.GiaSauGiamGia * 10) VNĐ </p>

            }
            else
            {
                <p>Giá:  @String.Format("{0:0,0}", @Model.GiaSp) VNĐ</p>
            }
        </h4>

        <div class="mb-3 mt-3 mr-5 mb-5">
            <a class="btn btn-primary" href="@Url.Action("AddProduct", "GioHang", new{ MaSP = Model.MaSP })">
                Đặt mua
            </a>
            @if (Session["UserID"] != null)
            {
                @Html.ActionLink("Thêm vào danh sách yêu thích", "AddToFavorite", "YeuThich", new { productId = Model.MaSP }, new { @class = "btn btn-primary" })
            }
            else
            {
                <p>Hãy đăng nhập để thêm sản phẩm vào danh sách yêu thích.</p>
            }

            @*<button class="btn-mh">Thêm vào giỏ hàng</button>*@
        </div>
        <div class="bg-light p-4 " style="border-radius: 5px;border: 1px solid #e5e7eb">
            <h3>Thông tin sản phẩm</h3>
            <ul>
                <li>Mô tả: @Model.Mau.Tenmau, sản phẩm còn lại: @Model.Soluongton cái</li>
            </ul>
        </div>
        <hr />
    </div>

    <div class="container-fluid  p-3 text-center mt-4" style="background-color: #1A6DFF; color: white; font-size: 20px; font-weight: bold; ">Thông Tin Chi Tiết Sản Phẩm</div>
    <div class="container ">
        <h1>Đánh giá @Model.TenSP</h1>
        <p>Những nâng cấp lớn về hiệu năng, dung lượng pin, và trên hết là camera sau chính là những điểm khiến nó trở thành siêu phẩm trong phân khúc cao cấp. Dưới đây là những thông tin cần biết về dòng điện thoại vừa ra mắt của Samsung.</p>

        <h2>Thiết kế nguyên khối - kính sang trọng với độ bền tối ưu</h2>
        <p>Samsung Galaxy S22 Ultra đi theo ngôn ngữ thiết kế nguyên khối - kính cao cấp và sang trọng, vốn đã làm nên sự thành công của model tiền nhiệm. Chiếc máy có thiết kế mặt lưng đơn sắc tối giản nhưng không kém phần tinh tế, và màn hình tràn viền bao phủ gần như toàn bộ mặt trước, tạo nên trải nghiệm quan sát rộng rãi trên một thiết bị di động nhỏ gọn vừa tay cầm.</p>
        <p>Độ bền của máy được đảm bảo tối ưu không chỉ qua lớp vỏ nhôm nguyên khối Amor đánh bóng, mà còn qua kính cường lực Corning Gorilla Glass Victus+ bao phủ hai mặt trước và sau. Khung nhôm và kính hoạt động như bộ giáp bảo vệ điện thoại an toàn. Chiếc máy còn có khả năng chống bụi/nước đạt chuẩn IP68 giúp người dùng luôn an tâm khi dùng máy trong những điều kiện môi trường khác nhau.</p>
        <p><img src="~/Image/ip5.jpg" style="max-height:400px" class="w-100"></p>
    </div>

    @Html.Action("laysanphamtt", "SanPhams")
</div>

Views/SanPhams/laysanphamtt.cshtml
@using Doanphanmem.Models
@model IEnumerable<SanPham>
@*san pham dd*@
<div class="container-fluid mt-5">
    <div class="container-fluid  p-3 text-center mt-4" style="background-color: #1A6DFF; color: white; font-size: 20px; font-weight: bold; ">Các Sản Phẩm Tương Tự</div>

    <div class="row mt-3 p-5">
        @foreach (var sp in Model)
        {
            <div class="col-sm-3 mb-4">
                <div class="card">
                    <a href="@Url.Action("SP_giamgia", "SanPhams", new { id = sp.MaSP })">
                        <img src="~/Image/@sp.Hinh1" class="card-img-top" alt="Iphone">

                        <div class="card-body">
                            <h5 class="card-title">@sp.TenSP</h5>
                            <p class="card-text">@sp.GiaSp</p>
                            <div class="row">
                            </div>
                        </div>
                    </a>
                    <a style="margin-bottom:0px;" href="@Url.Action("AddProduct", "GioHang", new{ MaSP = sp.MaSP })">
                        Đặt mua
                    </a>
                </div>
            </div>
        }
    </div>