Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Doanphanmem.Models;

namespace Doanphanmem.Controllers
{
    public class CategoriesController : Controller
    {
        private QL_CHDTEntities db = new QL_CHDTEntities();

        // GET: Categories
 

        public ActionResult Index(String SearchString)
        {
            if (Session["taikhoan"] == null)
                return RedirectToAction("Login", "Account");
 
            var phanloai = db.PhanLoai.Include(v => v.SanPham);

            if (!String.IsNullOrEmpty(SearchString))
            {
                phanloai = phanloai.Where(s => s.Tenloai.Contains(SearchString));
            }
            {
                Console.WriteLine("Không tìm thấy sản phẩm nào");
            }
            return View(phanloai.ToList());
        }



        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhanLoai phanLoai = db.PhanLoai.Find(id);
            if (phanLoai == null)
            {
                return HttpNotFound();
            }
            return View(phanLoai);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Tenloai,MaLoai,HinhLoai")] PhanLoai phanLoai,
            HttpPostedFileBase HinhLoai)
        {
            if (ModelState.IsValid)
            {
                if(HinhLoai != null)
                {
                    //Lấy tên file của hình được up lên
                    var fileNameLoai = Path.GetFileName(HinhLoai.FileName);
                    //Tạo đường dẫn tới file
                    var path = Path.Combine(Server.MapPath("~/Image/Loai"), fileNameLoai);
                    //Lưu tên
                    phanLoai.HinhLoai = fileNameLoai;
                    //Save vào Images Folder
                    HinhLoai.SaveAs(path);
                }
                db.PhanLoai.Add(phanLoai);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(phanLoai);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhanLoai phanLoai = db.PhanLoai.Find(id);
            if (phanLoai == null)
            {
                return HttpNotFound();
            }
            return View(phanLoai);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Tenloai,MaLoai,HinhLoai")] PhanLoai phanLoai,
        HttpPostedFileBase HinhLoai)
        {
            if (ModelState.IsValid)
            {

                if (HinhLoai != null)
                {
                    //Lấy tên file của hình được up lên
                    var fileNameLoai = Path.GetFileName(HinhLoai.FileName);
                    //Tạo đường dẫn tới file
                    var path = Path.Combine(Server.MapPath("~/Image/Loai"), fileNameLoai);
                    //Lưu tên
                    phanLoai.HinhLoai = fileNameLoai;
                    //Save vào Images Folder
                    HinhLoai.SaveAs(path);
                }
                db.Entry(phanLoai).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(phanLoai);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PhanLoai phanLoai = db.PhanLoai.Find(id);
            if (phanLoai == null)
            {
                return HttpNotFound();
            }
            return View(phanLoai);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PhanLoai phanLoai = db.PhanLoai.Find(id);
            db.PhanLoai.Remove(phanLoai);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Categories/Create.cshtml
@model Doanphanmem.Models.PhanLoai

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm("Create", "Categories", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4 style="text-align:center">Thêm loại sản phẩm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @*@Html.LabelFor(model => model.Tenloai, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-2">
            <p> Tên hãng </p>
        </div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Tenloai, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Tenloai, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @*@Html.LabelFor(model => model.HinhLoai, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-2">
            <p> Hình ảnh </p>
        </div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.HinhLoai, new { htmlAttributes = new { @class = "form-control" } })
            <input type="file" name="HinhLoai" accept="image/*" />
            @Html.ValidationMessageFor(model => model.HinhLoai, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

 

Views/Categories/Delete.cshtml
@model Doanphanmem.Models.PhanLoai

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@*<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PhanLoai</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Tenloai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tenloai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhLoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhLoai)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>*@

<div class="modal" style="position: relative;display: block;z-index: 0;overflow-y: hidden;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Xóa loại sản phẩm?</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <i class="anticon anticon-close"></i>
                </button>
            </div>
            <div class="modal-body">
                <p>Bạn có chắc xóa sản phẩm @Model.Tenloai ?</p>
            </div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="modal-footer">
                    <a href="/Categories/Index" type="button" class="btn btn-default m-r-10" data-dismiss="modal">Close</a>
                    <input type="submit" value="Delete" class="btn btn-primary" />
                </div>
            }

        </div>
    </div>
</div>

Views/Categories/Details.cshtml
@model Doanphanmem.Models.PhanLoai

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div>
    <h4>PhanLoai</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Tenloai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tenloai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhLoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhLoai)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaLoai }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Categories/Edit.cshtml
@model Doanphanmem.Models.PhanLoai

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}



@using (Html.BeginForm("Edit", "Categories", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4 style="text-align:center">Sửa thông tin hãng sản phẩm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-2">
                <p> Tên hãng </p>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tenloai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tenloai, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.MaLoai)

        <div class="form-group">
            <div class="col-md-2">
                <p> Hình ảnh </p>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.HinhLoai, new { htmlAttributes = new { @class = "form-control" } })
                <input type="file" name="HinhLoai" accept="image/*" />
                @Html.ValidationMessageFor(model => model.HinhLoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

 

Views/Categories/Index.cshtml
@model IEnumerable<Doanphanmem.Models.PhanLoai>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";

}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a href="~/Admin/" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Dashboard</a>
            <span class="breadcrumb-item active">Quản lý danh mục</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h2 class="header-title" style="text-align:center;">Quản lý danh mục</h2>
        <div class="row m-b-30">
            <div class="col-lg-12 text-right">
                <a href="/Categories/Create" class="btn btn-primary">
                    <i class="anticon anticon-plus-circle m-r-5"></i>
                    <span>Thêm mới</span>
                </a>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Tên loại</th>
                        <th>Hình</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                #@item.MaLoai
                            </td>
                            <td>@item.Tenloai</td>
                            <td><img src="~/Image/Loai/@item.HinhLoai" style="height:60px;width:60px" /></td>
                            <td class="text-right">
                                <a href="/Categories/Edit/@item.MaLoai" class="btn btn-icon btn-hover btn-sm btn-rounded pull-right">
                                    <i class="anticon anticon-edit"></i>
                                </a>
                                <a href="/Categories/Delete/@item.MaLoai" class="btn btn-icon btn-hover btn-sm btn-rounded">
                                    <i class="anticon anticon-delete"></i>
                                </a>
                            </td>
                        </tr>

                    }
                </tbody>
            </table>
        </div>
    </div>
</div>